### PR TITLE
Add heroku configurations and update ReadMe file.

### PR DESCRIPTION
**Pull request by geneowak**
## Description
Configure Heroku deployment

All pull requests should be related to open issues. Indicate the issue(s) below and remove this line:
Fixes #(17)

## How Has This Been Tested?
By visiting https://b4sdg-team269.herokuapp.com/

## Screenshots
hosted api

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have added necessary inline code documentation
- [] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by onabright — DISMISSED** [review]
Looks good.

**Comment by geneowak** [comment]
Wait to merge the PR, am making tests to ensure that the deployed app works well

**Comment by geneowak** [comment]
I was able to run the migrations and seed the database, I think we are now good to go

**Comment by geneowak** [comment]
All the defined endpoints work well on my side (tested using insomnia). Do check them out to verify before merging

**Review by MutegekiHenry — APPROVED** [review]
Thanks @geneowak for this upgrade

**Comment by geneowak** [comment]
> Looks good.

@onabright are we good to merge?

**Review by onabright — APPROVED** [review]
Looks good.

**Pull request merged**
