### PR TITLE
Setup auth and update the files.

### PR DESCRIPTION
**Pull request by geneowak**
## Description
Please include a summary of the change and relevant motivation and context. 
- Added authentication.
- Setup CRUD user's controller.
- Added linter.
- Updated README.
- Added UserSeeder.

## List any dependencies that are required for this change.
- Running `composer install` will update the dependencies

#### Screenshots
Screenshot from 2020-05-19 10-44-13
Screenshot from 2020-05-19 10-44-19
Screenshot from 2020-05-19 10-44-25
Screenshot from 2020-05-19 10-44-59
Screenshot from 2020-05-19 10-46-07
Screenshot from 2020-05-19 10-46-12

## How Has This Been Tested?
- I've update the README with these details

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by onabright — DISMISSED** [review]
@geneowak looks good! Good work!

**Review by microsoftjulius — DISMISSED** [review]
@geneowak it looks nice and easy to understand.

**Review by MutegekiHenry — DISMISSED** [review]
@geneowak good stuff

**Comment by MutegekiHenry** [comment]
@geneowak kindly address the conflicts before merge, caused by an earlier merged PR

**Comment by onabright** [comment]
@MutegekiHenry please review the PR again. I have sorted out the merge conflicts.

**Review by onabright — APPROVED** [review]
This is fine. I am working on the linting issues.

**Comment by MutegekiHenry** [comment]
ok let me review

**Review by MutegekiHenry — APPROVED** [review]

**Pull request merged**
