### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by microsoftjulius**
[docs] : Added my details under the read me file

### CODE REVIEW

**Comment by lewikeezy** [comment]
Check the line above which talks about screenshot, if there are no screen shots then you can delete that line, else everything other thing is okay

**Review by lewikeezy — CHANGES_REQUESTED** [review]
Check the line above which talks about screenshot, if there are no screen shots then you can delete that line, else everything other thing is okay

**Review by geneowak — APPROVED** [review]

**Review by onabright — APPROVED** [review]
All good.

**Comment by geneowak** [comment]
@onabright let's do away with the lint checks for now, they are not necessary as they don't affect the execution of the project

**Comment by MutegekiHenry** [comment]
This PR has dragged

**Review by MutegekiHenry — APPROVED** [review]

**Pull request merged**
